server:
  port: 8081
  servlet:
    context-path: /notification
spring:
  application:
    name: notify-service
  kafka:
    bootstrap-servers: ${DBKK_CONNECTION:kafka}:9094
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  data:
    mongodb:
      uri: mongodb://localhost:27017/notification-service?authSource=admin

brevo:
  api-key: ${BREVO_API_KEY}
  sender-email: ${BREVO_SENDER_EMAIL}
  sender-name: Shopping